theme: jekyll-theme-minimal
title: Conversation AI
description: Conversation AI is a collaborative research effort exploring ML as a tool for better discussions online.
google_analytics: UA-37043857-13
avatar: https://avatars2.githubusercontent.com/u/23317692?v=3&u=3319301a436f2b42d9c4fa89370ddc2e40c0feea
